apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.metallbConfig.poolName | default "default-pool" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - {{ .Values.metallbConfig.ipRange }}
