# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
k8_ip: 192.168.100.73
image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent
mfmongo:
  db_name: mfmongo
  db_port: 27017
  db_url: mfdb
  pvc: mfmongopvc
  mongostoragesize: 5Gi
mfrabbitmq:
  name: mfrabbitmq
  port: 5672
  adminport: 15672
  adminserviename: mfrabbitmqadmin
keycloak:
  name: keycloak
  pvc: keycloakpvc
  port: 8080
  keycloakstoragesize: 1Gi
mfinstruments:
  mf_http_port: 7001
  mf_name: mfinstruments
mftransactions:
  mf_http_port: 7002
  mf_name: mftransactions
mfmarketdata:
  mf_http_port: 7003
  mf_name: mfmarketdata
mfvaluation:
  mf_http_port: 7004
  mf_name: mfvaluation
mfcomposite:
  mf_http_port: 7009
  mf_name: mfcomposite
mffrontend:
  mf_http_port: 80
  mf_name: mffrontend
  pvc: mffeconfigpvc
  configstoragesize: 50Mi
mflogstream:
  mf_http_port: 30036
  mf_name: mflogstream
pv:
  localstorage: /opt/mf
  nasstorage: /mnt/data/mf
mfshell:
  name: mfshell
minecraft:
  name: minecraft
  image: itzg/minecraft-server
  pvc: minecraftpvc
  http_port: 25565
  http_port_ext: 30299
  storagesize: 1Gi
  storagepath: /mnt/data/minecraft
