# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent
mfcomposite:
  mf_http_port: 7005
  mf_name: mfcomposite
mfmongo:
  db_name: mfmongo
  db_port: 27017
  db_url: mfdb
  pvc: mfmongopvc
  mongostoragesize: 5Gi
mfrabbitmq:
  name: mfrabbitmq
  port: 5672
  adminport: 15672
  adminserviename: mfrabbitmqadmin
mfinstruments:
  mf_http_port: 7001
  mf_name: mfinstruments
pv:
  localstorage: /opt/mf
