# Centralized Backup Configuration for External USB Drive via Samba
backup:
  enabled: true
  #schedule: "10 1 * * *"
  schedule: "53 * * * *"
  useSamba: true
  sambaServer: "192.168.100.81"
  sambaShare: "external-backup"
  image: alpine:latest

  targets:
    nextcloud:
      enabled: true
      namespace: nextcloud
      pvc: nextcloud-pvc
      sourceSubPath: "data"
      include:
        - "__groupfolders/***"
        - "*/files/***"
        - "*/"
      exclude:
        - "appdata_*"
        - "*"
      targetDir: nextcloud
    immich:
      enabled: true
      namespace: immich
      pvc: immich-pvc
      sourceSubPath: ""
      exclude:
        - "thumbs/"
        - "encoded-video/"
        - "lost+found/"
      targetDir: immich
    paperless:
      enabled: true
      namespace: paperless
      pvc: paperless-media-pvc
      sourceSubPath: ""
      exclude:
        - "documents/thumbnails/"
        - "lost+found/"
      targetDir: paperless
