{{- if .Values.kopia.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kopia-credentials
  namespace: default
  labels:
    app: kopia
type: Opaque
stringData:
  KOPIA_PASSWORD: {{ .Values.kopia.auth.kopiaPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.kopia.auth.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.kopia.auth.rootPassword | quote }}
{{- range $key, $target := .Values.kopia.targets }}
{{- if $target.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kopia-credentials
  namespace: {{ $target.namespace }}
  labels:
    app: kopia
    target: {{ $key }}
type: Opaque
stringData:
  KOPIA_PASSWORD: {{ $.Values.kopia.auth.kopiaPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ $.Values.kopia.auth.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.kopia.auth.rootPassword | quote }}
{{- end }}
{{- end }}
{{- end }}
