replicaCount: 1

mfrabbitmq:
  name: mfrabbitmq
  port: 5672
  adminport: 15672
  adminserviename: mfrabbitmqadmin
  user: user
  pw: guest
  pvc: mfrabbitmqpvc
  storagesize: 1Gi
  storageClassName: ""

mfmongo:
  db_name: mfmongo
  db_port: 27017
  db_url: mfdb
  pvc: mfmongopvc
  backup_pvc: mfmongobackuppvc
  mongostoragesize: 5Gi
  storageClassName: ""
  backupStorageClassName: ""

