replicaCount: 1
image:
  pullPolicy: IfNotPresent

mfrabbitmq:
  name: mfrabbitmq
  port: 5672
  adminport: 15672
  adminserviename: mfrabbitmqadmin
  user: user
  pw: guest
  pvc: mfrabbitmqpvc
  storagesize: 1Gi
  storageClassName: ""

mfmongo:
  db_name: mfmongo
  db_port: 27017
  db_url: mfdb
  pvc: mfmongopvc
  backup_pvc: mfmongobackuppvc
  mongostoragesize: 5Gi
  storageClassName: ""
  backupStorageClassName: ""

mfinstruments:
  mf_http_port: 7001
  mf_name: mfinstruments
mftransactions:
  mf_http_port: 7002
  mf_name: mftransactions
mfmarketdata:
  mf_http_port: 7003
  mf_name: mfmarketdata
mfvaluation:
  mf_http_port: 7004
  mf_name: mfvaluation
mfsecuritymetrics:
  mf_http_port: 7005
  mf_name: mfsecuritymetrics
mfcomposite:
  mf_http_port: 7009
  mf_name: mfcomposite
mffrontend:
  mf_http_port: 80
  mf_name: mffrontend
  config: |
    {
      "zones": [
        {
          "name": "Localhost",
          "identifier": "local",
          "backendurl": "http://localhost:30030",
          "openidurl": "http://localhost:30024",
          "logstreamurl": "ws://localhost:30036/ws/logs"
        },
        {
          "name": "Dev",
          "identifier": "dev",
          "backendurl": "http://localhost:30030",
          "openidurl": "http://192.168.100.73:30024",
          "logstreamurl": "ws://localhost:30036/ws/logs"
        },
        {
          "name": "Mock",
          "identifier": "mock",
          "backendurl": "na",
          "openidurl": "na",
          "logstreamurl": "na"
        }
      ],
      "defaultZone": "local"
    }
mflogstream:
  mf_http_port: 30036
  mf_name: mflogstream
mfshell:
  name: mfshell