replicaCount: 1

mfrabbitmq:
  name: mfrabbitmq
  port: 5672
  adminport: 15672
  adminserviename: mfrabbitmqadmin
  user: user
  pw: guest
  pvc: mfrabbitmqpvc
  storagesize: 1Gi
  storageClassName: ""



