# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

monitoring:
  persistence:
    storageClassName: ""
    prometheusSize: 5Gi
    grafanaSize: 2Gi
  prometheus:
    name: prometheus
    pvc: prometheus-pvc
    retention: 24h
  grafana:
    name: grafana
    pvc: grafana-pvc
    pw: admin


