# Default values for paperless chart.
paperless:
  secretKey: "paperless_secure_secret_key_homelab_cluster"
  filenameFormat: "{{ document_type }}/{{ created_year }}/{{ correspondent }}/{{ created }} - {{ title }}"
  filenameFormatRemoveNone: true
  persistence:
    dataSize: 5Gi
    mediaSize: 5Gi
    dbSize: 5Gi
  db:
    name: paperless-db
    pvc: paperless-db-pvc
    user: paperless
    database: paperless
    pw: vulkan
  redis:
    name: paperless-redis
  app:
    name: paperless
    dataPvc: paperless-data-pvc
    mediaPvc: paperless-media-pvc
  admin:
    user: admin
    pw: vulkan
    mail: admin@home.local
  oauth:
    clientSecret: ""
