apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.stage }}-{{ .Values.mffrontend.pvc }}
spec:
  storageClassName: {{ .Values.mffrontend.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mffrontend.configstoragesize }}

