apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mfrabbitmq.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mfrabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mfrabbitmq.name }}
    spec:
      containers:
        - name: {{ .Values.mfrabbitmq.name }}
          image: "{{ .Values.mfrabbitmq.image }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: {{ .Values.mfrabbitmq.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.mfrabbitmq.user }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.mfrabbitmq.pw }}"
          volumeMounts:
            - name: mfrabbitmqdata
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: mfrabbitmqdata
          persistentVolumeClaim:
            claimName: {{ .Values.mfrabbitmq.pvc }}

