apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.stage }}-{{ .Values.mfmongo.pvc }}
spec:
  storageClassName: {{ .Values.mfmongo.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mfmongo.mongostoragesize }}

