apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.immich.app.name }}-config
  labels:
    app: {{ .Values.immich.app.name }}
data:
  immich.json: |
    {
      "storageTemplate": {
        "enabled": {{ .Values.immich.storageTemplate.enabled | default true }},
        "template": {{ .Values.immich.storageTemplate.template | default "{{y}}/{{MM}}/{{dd}}/{{filename}}" | quote }}
      },
      "oauth": {
        "enabled": true,
        "issuerUrl": "https://keycloak.hfischer.org/realms/home",
        "clientId": "immich",
        "clientSecret": "{{ .Values.immich.oauth.clientSecret | default "vulkan" }}",
        "autoRegister": true,
        "buttonText": "Login with Keycloak"
      }
    }
