apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.immich.app.name }}-config
  labels:
    app: {{ .Values.immich.app.name }}
data:
  immich.json: |
    {
      "oauth": {
        "enabled": true,
        "issuerUrl": "https://keycloak.hfischer.org/realms/home",
        "clientId": "immich",
        "clientSecret": "{{ .Values.immich.oauth.clientSecret | default "vulkan" }}",
        "autoRegister": true,
        "buttonText": "Login with Keycloak"
      }
    }
