master_ip: 192.168.100.85
image:
  repository: nexus.192.168.100.85.nip.io:31003/repository/mydockerrepo/
stage: prod
replicaCount: 0
mfrabbitmq:
  user: user
  pw: vulkan
  adminname: mfrabbitmqadmin
  storageClassName: longhorn-ssd

mfshell:
  enabled: false

mfmongo:
  createPvc: true
  volumeName: dr-prod-mfmongopvc
  db_pw: vulkan
  backupenabled: false
  storageClassName: longhorn-ssd
  backupStorageClassName: longhorn-ssd

keycloak:
  issuerUri: "https://keycloak.hfischer.org/realms/myfinance"

ingressRoute:
  enabled: true
  host: "myfinance.hfischer.org"

mffrontend:
  config: |
    {
      "zones": [
        {
          "name": "Prod",
          "identifier": "prod",
          "backendurl": "https://myfinance.hfischer.org",
          "openidurl": "https://keycloak.hfischer.org",
          "logstreamurl": "wss://myfinance.hfischer.org/ws/logs"
        }
      ],
      "defaultZone": "prod"
    }
