apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mfcomposite.mf_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mfcomposite.mf_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mfcomposite.mf_name }}
    spec:
      containers:
        - name: {{ .Values.mfcomposite.mf_name }}
          image: "{{ .Values.image.repository }}mfcomposite:{{ .Values.mfframework.imageversion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}      
          tty: true
          env:
            - name: "api.common.version"
              value: "{{ .Values.mfframework.imageversion }}"
            - name: "spring.rabbitmq.port"
              value: "{{ .Values.mfrabbitmq.port_ext }}"
            - name: "server.port"
              value: "{{ .Values.mfcomposite.mf_http_port }}"
            - name: "app.mfinstruments.host"
              value: "{{ .Values.mfinstruments.mf_name }}"
            - name: "app.mfinstruments.port"
              value: "{{ .Values.mfinstruments.mf_http_port_ext }}"
            - name: "app.mftransactions.host"
              value: "{{ .Values.mftransactions.mf_name }}"
            - name: "app.mftransactions.port"
              value: "{{ .Values.mftransactions.mf_http_port_ext }}"
            - name: "app.mfmarketdata.host"
              value: "{{ .Values.mfmarketdata.mf_name }}"
            - name: "app.mfmarketdata.port"
              value: "{{ .Values.mfmarketdata.mf_http_port_ext }}"
            - name: "app.mfvaluation.host"
              value: "{{ .Values.mfvaluation.mf_name }}"
            - name: "app.mfvaluation.port"
              value: "{{ .Values.mfvaluation.mf_http_port_ext }}"
