{{ if .Values.mfbasedeployment_non_cluster }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.keycloak.storageClassName }}
spec:
  storageClassName: {{ .Values.keycloak.storageClassName }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.keycloak.keycloakstoragesize }}
  hostPath:
    path: {{ .Values.pv.nasstorage }}/{{ .Values.stage }}_keycloak
    type: Directory

{{ end }}