apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.stage }}-{{ .Values.keycloak.pvc }}
spec:
  storageClassName: {{ .Values.stage }}-keycloakstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.keycloakstoragesize }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.stage }}-keycloakstorage
spec:
  storageClassName: {{ .Values.stage }}-keycloakstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.keycloak.keycloakstoragesize }}
  hostPath:
    path: {{ .Values.pv.nasstorage }}/{{ .Values.stage }}_keycloak
    type: Directory