{{ if .Values.mfbasedeployment_non_cluster }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  #this defines which pod is going to be presented by this service
  selector:
    app: {{ .Values.keycloak.name }}
  ports:
    - name: {{ .Values.keycloak.name }}
      port: {{ .Values.keycloak.port }}
      nodePort: {{ .Values.keycloak.port_ext }}
  type: NodePort

{{ end }}
{{ if .Values.mfbasedeployment_cluster }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  #this defines which pod is going to be presented by this service
  selector:
    app: {{ .Values.keycloak.name }}
  ports:
    - name: {{ .Values.keycloak.name }}
      port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port_ext }}
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: "keycloak.{{ .Values.master_ip }}.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.keycloak.port }}     

{{ end }}