{{ if eq .Values.deployment "full" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mfinstruments.mf_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mfinstruments.mf_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mfinstruments.mf_name }}
    spec:
      containers:
        - name: {{ .Values.mfinstruments.mf_name }}
          image: "{{ .Values.image.repository }}mfinstruments:{{ .Values.mfinstruments.imageversion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          env:
            - name: "server.host"
              value: "{{ .Values.k8_ip }}"
            - name: "server.port"
              value: "{{ .Values.mfinstruments.mf_http_port_ext }}"
            - name: "spring.data.mongodb.port"
              value: "{{ .Values.mfmongo.db_port_ext }}"
            - name: "api.common.version"
              value: "{{ .Values.mfinstruments.imageversion }}"
            - name: "spring.rabbitmq.port"
              value: "{{ .Values.mfrabbitmq.port_ext }}"
{{ end }}