apiVersion: batch/v1
kind: CronJob
metadata:
  name: mfpriceimport
spec:
  schedule: "{{ .Values.mfshell.priceimportschedule }}"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.mfshell.name }}
              image: "{{ .Values.image.repository }}mfshell:{{ .Values.mfshell.imageversion }}"
              args: ["import-market-data"]
              env:
                - name: "spring.rabbitmq.port"
                  value: "{{ .Values.mfrabbitmq.port_ext }}"
                - name: "job.name"
                  value: "importMarketData"
          restartPolicy: OnFailure
      backoffLimit: 4