apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mfvaluation.mf_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mfvaluation.mf_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mfvaluation.mf_name }}
    spec:
      containers:
        - name: {{ .Values.mfvaluation.mf_name }}
          image: "{{ .Values.image.repository }}mfvaluation:{{ .Values.mfvaluation.imageversion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          env:
            - name: "api.common.version"
              value: "{{ .Chart.AppVersion }}"
            - name: "spring.data.mongodb.host"
              value: "{{ .Values.k8_ip }}"
            - name: "spring.data.mongodb.port"
              value: "{{ .Values.mfmongo.db_port_ext }}"
            - name: "spring.rabbitmq.port"
              value: "{{ .Values.mfrabbitmq.port_ext }}"