{{ if eq .Values.deployMinecraft "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.minecraft.pvc }}
spec:
  storageClassName: minecraftstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minecraft.storagesize }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraftstorage
spec:
  storageClassName: minecraftstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.minecraft.storagesize }}
  hostPath:
    path: {{ .Values.minecraft.storagepath }}
    type: Directory
{{ end }}