apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.stage }}-{{ .Values.mfmongo.pvc }}test
spec:
  storageClassName: {{ .Values.stage }}-mfmongostoragetest
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mfmongo.mongostoragesize }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.stage }}-localmongostoragetest
spec:
  storageClassName: {{ .Values.stage }}-mfmongostoragetest
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.mfmongo.mongostoragesize }}
  hostPath:
    path: {{ .Values.pv.localstorage }}/{{ .Values.stage }}test
    type: Directory