apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mfmongo.db_name }}
spec:
  #this defines which pod is going to be presented by this service
  selector:
    app: {{ .Values.mfmongo.db_name }}
  ports:
    - name: {{ .Values.mfmongo.db_name }}
      port: {{ .Values.mfmongo.db_port }}
      nodePort: {{ .Values.mfmongo.db_port_ext }}
  type: NodePort