# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metallbConfig:
  poolName: default-pool
  l2AdvertisementName: default-l2-adv
  ipRange: 192.168.100.30-192.168.100.35
