# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metallbConfig:
  poolName: default-pool
  l2AdvertisementName: default-l2-adv
  ingressIp: 192.168.100.30
  generalIpRange: 192.168.100.31-192.168.100.33
