master_ip: 192.168.100.85

nextcloud:
  replicaCount: 0
  persistence:
    createPvc: true
    storageClassName: longhorn-ssd
    nextcloudSize: 10Gi
    dbSize: 5Gi
    volumeName: dr-nextcloud-pvc
    dbVolumeName: dr-nextcloud-db-pvc
  db:
    pw: vulkan
  app:
    adminPw: vulkan
