stage: prod
mfcomposite:
  mf_http_port_ext: 30038
mfmongo:
  db_pw: vulkan
  db_port_ext: 30039
mfrabbitmq:
  user: user
  pw: vulkan
  port_ext: 30031
  adminport_ext: 30032
mfinstruments:
  mf_http_port_ext: 30034