stage: prod
mfcomposite:
  mf_http_port_ext: 30048
mfmongo:
  db_pw: vulkan
  db_port_ext: 30049
mfrabbitmq:
  user: user
  pw: vulkan
  port_ext: 30041
  adminport_ext: 30042
mfinstruments:
  mf_http_port_ext: 30044
mftransactions:
  mf_http_port_ext: 30046
mfvaluation:
  mf_http_port_ext: 30045