stage: test
master_ip: 192.168.100.81
mfbasedeployment: true
mffulldeployment: false
minecraftdeployment: false
mfbasedeployment_non_cluster: false
mfbasedeployment_cluster: true
nextclouddeployment: false
mfrabbitmq:
  user: user
  pw: vulkan
  port_ext: 30121
  adminname: mfrabbitmqadmin
  adminport_ext: 30122
mfmongo:
  db_pw: vulkan
  db_port_ext: 30123
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12)
    # │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday to Saturday;
    # │ │ │ │ │                                       7 is also Sunday on some systems)
    # │ │ │ │ │
    # │ │ │ │ │
  # * * * * *  command to execute
  dumpschedule: "1 22 * * 0" 
  #dumpschedule: "53 * * * *"  
keycloak:
  pw: vulkan
  port_ext: 30124
  storageClassName: longhorn-ssd
mfcomposite:
  mf_http_port_ext: 30130
mfinstruments:
  mf_http_port_ext: 30131
mftransactions:
  mf_http_port_ext: 30132
mfmarketdata:
  mf_http_port_ext: 30133
mfvaluation:
  mf_http_port_ext: 30134
mffrontend:
  mf_http_port_ext: 30135
mflogstream:
  mf_http_port_ext: 30136
mfsecuritymetrics:
  mf_http_port_ext: 30137
mfshell:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12)
    # │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday to Saturday;
    # │ │ │ │ │                                       7 is also Sunday on some systems)
    # │ │ │ │ │
    # │ │ │ │ │
  # * * * * *  command to execute
  importtimeseriesweeklyschedule: "1 22 * * 1,2,3,4,5"
  importsecuritymetricsschedule: "1 22 * * 6,0"
  importprevcloseschedule: "1 10 * * *"
  processtransactionschedule: "1 23 * * *"

monitoring:
  enabled: true
  persistence:
    storageClassName: longhorn-ssd
  grafana:
    pw: vulkan

