apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.keycloak.pvc }}
spec:
  storageClassName: {{ .Values.keycloak.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.keycloakstoragesize }}
